import { useState } from "react";
import { ChevronDown } from "lucide-react";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";

function SectionHeading({ children }: { children: React.ReactNode }) {
  return (
    <h4 className="mb-2 mt-4 text-sm font-semibold tracking-tight text-ink">
      {children}
    </h4>
  );
}

export function MethodologySection() {
  const [open, setOpen] = useState(false);

  return (
    <Collapsible open={open} onOpenChange={setOpen}>
      <CollapsibleTrigger className="flex w-full items-center justify-between rounded-field px-1 py-2 text-left text-sm font-semibold text-ink hover:bg-black/5">
        <span>How this is calculated</span>
        <ChevronDown
          className={`h-4 w-4 text-muted transition-transform ${open ? "rotate-180" : ""}`}
        />
      </CollapsibleTrigger>
      <CollapsibleContent>
        <div className="pt-2 text-sm leading-relaxed text-ink/80">
          <SectionHeading>Pool A — OTA leakage recovery</SectionHeading>
          <p>
            Guests who wanted to book direct but ended up on an OTA. Recovered
            by providing a working, WhatsApp-native direct channel they can
            find and use.
          </p>
          <p className="mt-2">
            <em className="text-ink">Formula:</em> Monthly bookings × OTA share
            × recovery rate = recovered bookings. Per-booking uplift = (ADR ×
            (1 − discount) × (1 − BookDirect.my commission)) − (ADR × (1 − OTA
            commission)). Annual uplift = recovered bookings × per-booking
            uplift × 12.
          </p>
          <p className="mt-2">
            <em className="text-ink">Key assumption — recovery rate:</em> The
            default of 11% is the bottom of the 11–15% range established in
            independent lodging research — a deliberately conservative anchor.
            Rates trend higher (up to 22%) for logistically complex
            destinations like Sabah, where pre-booking inquiries are mandatory.
          </p>

          <SectionHeading>Pool B — Direct channel uplift</SectionHeading>
          <p>
            Existing direct-intent guests who tried to book directly but
            abandoned due to slow response times, clunky mobile booking pages,
            or unanswered FAQ questions. Recovered by replacing that
            infrastructure with a WhatsApp-native flow.
          </p>
          <p className="mt-2">
            <em className="text-ink">Formula:</em> Direct bookings × direct
            channel lift rate = newly captured bookings. Per-booking
            contribution = ADR × (1 − discount) × (1 − BookDirect.my
            commission). Annual uplift = newly captured × contribution × 12.
          </p>
          <p className="mt-2">
            <em className="text-ink">
              Key assumption — direct channel lift rate:
            </em>{" "}
            The default of 5% is the bottom of the 5–10% range suggested by
            published case studies on WhatsApp-native conversion uplift — a
            deliberately conservative anchor.
          </p>

          <SectionHeading>
            What the calculator deliberately excludes
          </SectionHeading>
          <p>
            Even the combined figure is a conservative floor. It does not
            count:
          </p>
          <ul className="ml-4 mt-2 list-disc space-y-1">
            <li>
              <em className="text-ink">
                New demand generated by the BookDirect.my page ranking on
                Google
              </em>{" "}
              — true net new bookings that weren't previously part of the
              hotel's funnel.
            </li>
            <li>
              <em className="text-ink">
                Upsells via the persistent WhatsApp thread
              </em>{" "}
              — higher room categories, extended stays, airport transfers, F&B,
              experiences.
            </li>
            <li>
              <em className="text-ink">Reduced front-desk workload</em> — fewer
              calls and manual inquiries handled by reception.
            </li>
            <li>
              <em className="text-ink">Long-term compounding</em> — the FAQ
              system accumulates new answers over time, each of which becomes a
              permanent SEO asset. Year-on-year capture grows as the page
              matures.
            </li>
          </ul>
          <p className="mt-2">
            The real number is likely meaningfully higher than shown. These
            figures represent what can be defended with today's research and
            today's page authority.
          </p>

          <SectionHeading>Sensitivity</SectionHeading>
          <p>
            All inputs are adjustable under "Advanced assumptions." If your
            hotel has better current direct conversion, set the direct channel
            lift rate lower. If your current OTA infrastructure is above
            industry norm, lower the recovery rate. The math stays honest under
            any set of plausible inputs.
          </p>
        </div>
      </CollapsibleContent>
    </Collapsible>
  );
}
